# Generated by Django 5.0.4 on 2024-04-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='default.png', null=True, upload_to='categories/%y/%m/%d/'),
        ),
    ]
