# Generated by Django 5.0.4 on 2024-04-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_alter_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='QWE', verbose_name='Короткое описание'),
            preserve_default=False,
        ),
    ]
