# Generated by Django 5.0.4 on 2024-05-19 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0009_alter_course_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsAndEvents',
        ),
    ]
