# Generated by Django 5.0.4 on 2024-05-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogItem',
        ),
    ]
