# Generated by Django 5.0.4 on 2024-05-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_short_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.png', upload_to='blogs/', verbose_name='Изображение'),
        ),
    ]
