# Generated by Django 5.0.4 on 2024-05-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.png', upload_to='blogs/%y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
