# Generated by Django 5.0.4 on 2024-04-19 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_remove_coursecontent_course_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseitem',
            name='course_item',
        ),
        migrations.AddField(
            model_name='coursecontent',
            name='course_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='course_items', to='course.courseitem'),
            preserve_default=False,
        ),
    ]
